// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SpeedManager","status":true,"description":"v1.1 Allows you to manage default movement speeds.","parameters":{"Move Speed":"3","Dash Speed":"1","Boat Speed":"4","Ship Speed":"5","Airship Speed":"6","Agility Based":"false","Distance Per Frame":"Math.pow(2, this.realMoveSpeed()) / 256;"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}}
];
